/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totp.gui;

import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static sun.applet.AppletResourceLoader.getImage;
import totp.a2f.GoogleAuthenticator;
import totp.bd.Configuracion;
import totp.bd.ManagerConfiguracionDB;
import totp.bd.ManagerUsuarioDB;
import totp.bd.Usuario;
import totp.principal.Main;
//import totp.ui.MostrarQR;
//import totp.ui.PantallaPrincipal;

/**
 *
 * @author ivancho
 */
public class PanelQR extends javax.swing.JPanel {

    /**
     * Creates new form PanelQR
     */
    public PanelQR() {
        initComponents();
        mostrarQR();
    }
    
    public PanelQR(Configuracion configuracion){
        initComponents();
        mostrarQR(configuracion);
    }
    
    public void mostrarQR(){
        ManagerConfiguracionDB mcdb = new ManagerConfiguracionDB();
        Configuracion configuracion = mcdb.consultarRegistro(Main.usuario.getEmail());
        String qr;
        if(configuracion.getTipo().compareToIgnoreCase("HOTP")==0) qr = GoogleAuthenticator.getQRUrlHOTP(configuracion.getEmail(),Main.usuario.getClave_secreta(),configuracion.getContador_hotp());
        else qr = GoogleAuthenticator.getQRUrl(Main.usuario.getNombre(), Main.usuario.getEmail(), Main.usuario.getClave_secreta());
        lblClaveSecreta.setText(Main.usuario.getClave_secreta());
        try {
            Image img=getImage(new URL(qr));
            lblImagen.setIcon(new ImageIcon(img));
            repaint();
        } catch (MalformedURLException ex) {
            //Logger.getLogger(MostrarQR.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error" + ex.getMessage());
        }
    }
    
    
    public void mostrarQR(Configuracion configuracion){
        String qr = GoogleAuthenticator.getQRUrlConfiguracion(Main.usuario.getClave_secreta(),configuracion);
        lblClaveSecreta.setText(Main.usuario.getClave_secreta());
        try {
            Image img=getImage(new URL(qr));
            lblImagen.setIcon(new ImageIcon(img));
            repaint();
        } catch (MalformedURLException ex) {
            //Logger.getLogger(MostrarQR.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Error" + ex.getMessage());
        }
    }
    
    
    
    
    
    
    
//https://chart.googleapis.com/chart?chs=200x200&chld=M%7C0&cht=qr&chl=otpauth://totp/ivan@example.com?secret=RQCS4KLYL7HJFP54JI4YZQPU5U442PVD    
//https://chart.googleapis.com/chart?chs=200x200&chld=M%7C0&cht=qr&chl=otpauth://hotp/demo@example.com?secret=JBSWY3DPK5XXE3DEJ5TE6QKUJA

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblClaveSecreta = new javax.swing.JLabel();

        setBackground(java.awt.Color.darkGray);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(123, 234, 12));
        jLabel1.setText("Escanear el siguiente código QR con Google Authenticator:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblImagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 234, 12));
        jLabel3.setText("Nota: si no puedes escanear el código, ingrésalo manualmente:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        lblClaveSecreta.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lblClaveSecreta.setForeground(java.awt.Color.white);
        lblClaveSecreta.setText("RQCS4KLYL7HJFP54JI4YZQPU5U442PVD");
        lblClaveSecreta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblClaveSecreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblClaveSecreta;
    private javax.swing.JLabel lblImagen;
    // End of variables declaration//GEN-END:variables
}
